### ISSUE TITLE
Automatic Upload to S3 Fails 

### ISSUE THREAD

**Issue by ajzhou** [awslabs/aws-mobile-appsync-sdk-ios#45]
Hi I am reopening an issue discussed previously (#25). I followed the updated instructions (https://awslabs.github.io/aws-mobile-appsync-sdk-ios/#complex-objects) to a tee and still experienced no success with automatically uploading to S3. I can see that there is an S3Object in my dynamoDB table but nothing gets uploaded to my S3 bucket. I tried uploading the same file using TransferUtility and it works, so I'm not sure what the issue is.

**Comment by br3nt0n** [comment]
Have you tried making the S3Object a top level item? I've had success doing it with something like this:
`create(post: Post, imageToUpload: S3ObjectInput)`

**Comment by josecalles** [comment]
Also experiencing the same issue. I am seeing the S3 object in Dynamo but nothing ever gets uploaded to the bucket. I am saving a `UIImage` to my local documents directory and then passing in `imageFilePath.absoluteString` to the `localUri` parameter. I saw it was mentioned in another thread that the transfer utility only searches the root directory for the file. Can this be causing the issue? Since I'm instead saving it to the documents directory.

**Comment by richienko** [comment]
As I know, the br3nt0n is right, S3Object has to be in top level item.

For example if you have:
`create(post: PostInput)`

and PostInput is
```
type Post {
  	id: ID!
  	author: String!
  	title: String
  	file: S3Object
  }
```

change mutation to:
`create(post: PostInput, file: S3ObjectInput)`

and PostInput to:
```
type Post {
  	id: ID!
  	author: String!
  	title: String
  }
```

**Reason**:
In `AppSyncComplexObjectsInterceptor`, when deciding if operation should upload S3Object, this  condition has to be met:
`request.operation.queryDocument().contains("S3ObjectInput")`

You can check manually for string "S3ObjectInput" in generated Apollo source file for mutation.
If String object `OPERATION_DEFINITION` in said mutation source doesn't contain string "S3ObjectInput", interceptor will simply ignore it and will not upload file.

**Comment by palpatim** [comment]
Commenting on this old issue to note that this issue is fixed as of release 2.9.0.

**Comment by mopilo** [comment]
Ah have been experiencing this issue since yesterday and still not solved. using the latest release 3.1.2
