### ISSUE TITLE
Optimistic update: Error at path "<query_with_pagination>.nextToken": missingValue

### ISSUE THREAD

**Issue by richienko** [awslabs/aws-mobile-appsync-sdk-ios#51]
The query with argument within optimistic update closure will fail with "missingValue" message.
The query is paginated.

**Version** of AppSync:
`2.6.18`

**Message** I'm getting:
`Error at path "listJobsByCustomer.nextToken": missingValue`

**Mutation**:
`updateJob(input: UpdateJobInput!): Job`

**Query** called in optimistic update closure:
`listJobsByCustomer(customerId: String, first: Int, after: String): JobConnection`

**JobConnection**:
```
type JobConnection {
	items: [Job]
	nextToken: String
}
```

**Code**:
```
let mutation = UpdateJobMutation(input: input)

appSyncClient?.perform(mutation: mutation, optimisticUpdate: { (transaction) in
	do {
		// Update our normalized local store immediately for a responsive UI
		let query = ListJobsByCustomerQuery(customerId: "customerId", limit: 1)
		try transaction?.update(query: query) {
			(data: inout ListJobsByCustomerQuery.Data) in

			for i in 0..<(data.listJobsByCustomer?.items)!.count {
				if data.listJobsByCustomer?.items?[i]?.id == input.id {
					data.listJobsByCustomer?.items?[i]?.status = input.status!
				}
			}
		}
	} catch let exception {
		print("UpdateJobMutation Error updating the cache with optimistic response: \(exception.localizedDescription)")
	}
}) { (result, error) in
	if let error = error as? AWSAppSyncClientError {
		print("Error occurred: \(error.localizedDescription )")
		return
	}
	
	if let res = result {
		print("UpdateJobInfo result: \(res)")
	}
	
	self.handleNetworkStateOnResult(online: true)
}
```

**Comment by wir349** [comment]
I'm having a similar issue, except I'm not using pagination.

**Comment by koingruc** [comment]
Is this bug is fixed in Release v2.6.18 ? Thanks

**Comment by richienko** [comment]
@koingruc no, it's not fixed, I'm using 2.6.18 and it's bugged

**Comment by koingruc** [comment]
@richienko Thank you for the information.

**Comment by Foefirelord** [comment]
Same issue. Simply trying to implement a basic mutation with the sample code provided on the official doc page, yet getting "missingValue" from `transaction?.update`.

**Comment by koingdev** [comment]
For those who have problem with `optimistic UI missing value`. I've found one trick to temporary solve the issue by passing parameter using `Custom Request Header` from client app.
Before, your query would look like this : `allDiaries(author: String): [Diary]`.
Just change it to => `allDiaries: [Diary]`. So your `request mapping would look like below:`
```
{
    "version" : "2017-02-28",
    "operation" : "Scan",
    "filter" : {
        "expression" : "author = :author",
        "expressionValues" : {
            ":author" : { "S" : "$context.request.headers.author" }
        }
    }
}
```

**Comment by hemant236** [comment]
Any update on the issue, Is it fixed in latest 2.6.21

**Comment by koingruc** [comment]
@hemant236 Check this link.
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/master/CHANGELOG.md
If you have this issue, you can try my solution :) I solved it using `Request Header` instead of `Argument`

**Comment by hemant236** [comment]
Is their any other framework/class that I need to import for using `CognitoAuthProvider()` and `CognitoUserPoolManager`

**Comment by rohandubal** [comment]
This is now fixed with SDK Version `2.6.22`
